Repository intern-space-program/ksp, pull requests merged in 2020-07, with the labels that each got.

#53 52 create pull request template
  .github/pull_request_template.md
Labels: admin

#55 [fixes #54] pipfile python version fix
  Pipfile
  README.md
Labels: admin, urgent

#57 Changing Python version from 3.8 to 3.7 (MR #55)
  README.md
Labels: documentation

#60 39 preliminary ae procedure
  proc/ascent-entry/Ascent-Entry-Outline.md
  proc/ascent-entry/ES1.md
  proc/ascent-entry/ES2.md
Labels: documentation
